### ISSUE TITLE
JS output still emitted if type checking fails

### ISSUE THREAD

**Issue by robertknight** [CODEYA/node-shellscript-ts#32]
If a TypeScript file fails to typecheck, shellscript-ts will still generate JS output and cache it. Running the .ts file again will run the cached script without warning that compilation failed.

**Comment by eiichiro-takahashi** [comment]
Thank you, @robertknight. 
First of all, I am not good at English. Please forgive my poor English.

I fixed shellscript-ts ( https://github.com/CODEYA/node-shellscript-ts/pull/33 ) and publish shellscript-ts ver.1.0.12. If the problem didn't solved yet, please let me know.

**Comment by robertknight** [comment]
That fixed the problem, thanks @eiichiro-takahashi
